
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="ys"
#DISABLE_AUTO_UPDATE="true"
export UPDATE_ZSH_DAYS=13
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd".
plugins=(git git-extras symfony2 phing sudo composer)
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/var/www/safebeat-be/bin:/var/www/safebeat-be/vendor/bin"
source $ZSH/oh-my-zsh.sh
export EDITOR=vim
