version: '3.6'

services:
  nginx:
    container_name: safebeat_nginx
    build: ./docker/nginx
    image: guidopili/safebeat-be-nginx
    volumes:
      - .:/var/www/safebeat-be
    ports:
      - "80:80"
    links:
      - fpm:fpm

  fpm:
    container_name: safebeat_php
    image: guidopili/safebeat-be-php:latest
    user: safebeat-dev
    volumes:
      - .:/var/www/safebeat-be
    depends_on:
      - mysql
    ports:
      - "9000:9000"
      - "8090:8090"
    links:
      - mysql:mysql

  mysql:
    container_name: safebeat_mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: djRmqSxxdppt8rHV

  mercure:
    container_name: safebeat_mercure
    image: dunglas/mercure
    ports:
      - "3000:80"
    environment:
      JWT_KEY: PCdv6N6xPjPmmm6eVbt6sWYpZJp4Wju9
      ALLOW_ANONYMOUS: 1
      PUBLISH_ALLOWED_ORIGINS: "http://safebeat.io"
      CORS_ALLOWED_ORIGIN: "http://safebeat.io"
