parameters:
  env(MERCURE_PUBLISH_URL): ''
  env(MERCURE_JWT_SECRET): ''
  locale: 'en'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Safebeat\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Safebeat\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # Doctrine Repositories
  Safebeat\Repository\RefreshTokenRepository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Safebeat\Entity\RefreshToken

  Safebeat\Repository\WalletRepository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Safebeat\Entity\Wallet

  Safebeat\Repository\WalletPendingInvitationRepository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Safebeat\Entity\WalletPendingInvitation

  Safebeat\Repository\MoneyTransactionRepository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Safebeat\Entity\MoneyTransaction

  Safebeat\Repository\NotificationRepository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Safebeat\Entity\Notification

  Safebeat\Listener\TimeStampableListener:
    tags:
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: prePersist }

  Safebeat\Listener\ExceptionSubscriber:
    arguments:
      $env: '%kernel.environment%'

#  Safebeat\Listener\RequestValidationListener:
#    tags:
#      - { name: kernel.event_listener, event: kernel.controller, method: log }
